services:
  server:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://pgdb:5432/transactions
    networks:
      - springpgdb-net
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - springpgdb-net
    environment:
      - POSTGRES_DB=transactions
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

networks:
  springpgdb-net: